- 
  name: ansible project
  hosts: host1,host2
  become: root
  tasks:
   - name: install apache-web server
     yum:
       name: httpd
       state: present
   - name: start apache-web server
     services:
       name: httpd
       state: started
   - name: enable apache web server boot time
     services:
       name: httpd
       enabled: yes
   - name: creating a log directory.
     file:
       path: /root/log
       state: directory
   - name: creating apache.log file and writing message.
     file:
       path: /root/log/apache.log
       state: touch
   - name: code to write message in that file.
     lineinfile:
       path: /root/log/apache.log
       state: present
       line: 'apache is successfully installed'
   - name: create a web page
     file:
       path: /var/www/html/index.html
       state: touch
   - name: write html code.
     lineinfile:
       path: /var/www/html/index.html
       state: present
       line: '<html> <body> <h1> Akhil Surya </h1> </body> </html>'

      
